### ISSUE TITLE
Automatic img tag generation and completion of src attribute with generated file's name.

### ISSUE THREAD

**Issue by federicosan** [pkra/mathjax-node-svg2png#13]
MathJax-node had something very useful, it seemed to be able to get the png into the img tag for automatic inclusion into an HTML file.

I don't know if this addon has the same functionality or I would have to make it.

It is not clear were will the img be generated, is this generating a file or just a stream of data with the appropriate headers?

Thank you

**Comment by pkra** [comment]
> is this generating a file or just a stream of data with the appropriate headers?

As mentioned in https://github.com/pkra/mathjax-node-svg2png#use, this extends the mathjax-node API, adding to the returned object two keys containing strings: png with a base64 string encoded png, pngWidth with the width.

https://github.com/pkra/mathjax-node-svg2png/blob/125a0b2a81228cdf0ecfee21f2623453d610ecb1/lib/main.js#L79
